import type { Agent, ModelAsset, ModelRuntime, Voice } from "./types";

export function createDefaultWorkspace(now = new Date().toISOString()): {
  agents: Agent[];
  modelRuntimes: ModelRuntime[];
  modelAssets: ModelAsset[];
  voices: Voice[];
} {
  return {
    agents: [
      {
        id: "agent_reception",
        name: "Reception Agent",
        greeting: "Hi, this is LipiVoice. How can I help?",
        systemPrompt:
          "Answer concisely, ask one question at a time, and collect the caller's name.",
        language: "en",
        modelRuntimeId: "runtime_ollama",
        modelAssetId: "model_llama32_3b",
        voiceId: "voice_piper_amy",
        transcriberRuntimeId: "runtime_whisper_cpp",
        recordingEnabled: false,
        interruptionSensitivity: "medium",
        toolIds: [],
        knowledgeBaseIds: [],
        deploymentState: "draft",
        createdAt: now,
        updatedAt: now,
      },
    ],
    modelRuntimes: [
      {
        id: "runtime_ollama",
        kind: "llm",
        adapter: "ollama",
        endpoint: "http://127.0.0.1:11434",
        configuredState: "configured",
        healthStatus: "unknown",
        defaultModelId: "model_llama32_3b",
        concurrencyLimit: 1,
        hardwareHints: ["local"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_whisper_cpp",
        kind: "stt",
        adapter: "whisper_cpp",
        endpoint: "",
        configuredState: "not_configured",
        healthStatus: "missing_model",
        defaultModelId: "model_whisper_base_en",
        concurrencyLimit: 1,
        hardwareHints: ["cpu", "metal"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_piper",
        kind: "tts",
        adapter: "piper",
        endpoint: "",
        configuredState: "not_configured",
        healthStatus: "missing_model",
        defaultModelId: "voice_piper_amy",
        concurrencyLimit: 1,
        hardwareHints: ["cpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_energy_vad",
        kind: "vad",
        adapter: "energy_vad",
        endpoint: "local",
        configuredState: "configured",
        healthStatus: "healthy",
        defaultModelId: "energy_threshold_v1",
        concurrencyLimit: 4,
        hardwareHints: ["cpu"],
        createdAt: now,
        updatedAt: now,
      },
    ],
    modelAssets: [
      {
        id: "model_llama32_3b",
        runtimeId: "runtime_ollama",
        name: "llama3.2:3b",
        kind: "llm",
        family: "llama",
        version: "3.2",
        pathOrTag: "llama3.2:3b",
        license: "Meta Llama license",
        parameterSize: "3B",
        quantization: "provider default",
        languageSupport: ["en"],
        installedState: "unknown",
      },
      {
        id: "model_whisper_base_en",
        runtimeId: "runtime_whisper_cpp",
        name: "Whisper base.en",
        kind: "stt",
        family: "whisper",
        version: "base.en",
        pathOrTag: "ggml-base.en.bin",
        license: "MIT",
        parameterSize: "74M",
        quantization: "ggml",
        languageSupport: ["en"],
        installedState: "unknown",
      },
    ],
    voices: [
      {
        id: "voice_piper_amy",
        name: "Piper Amy",
        runtimeId: "runtime_piper",
        type: "builtin",
        language: "en-US",
        tags: ["local", "neutral"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
    ],
  };
}
