import type {
  Agent,
  Appointment,
  ConsentRecord,
  Customer,
  EvalDefinition,
  KnowledgeBase,
  KnowledgeDocument,
  ModelAsset,
  ModelRuntime,
  PhoneNumber,
  Ticket,
  Tool,
  TransferRecord,
  Voice,
  VoiceSample,
  WorkspaceSettings,
} from "./types";

interface RemoteWorkspaceOptions {
  now?: string;
  vllmEndpoint: string;
  vllmModel: string;
  lipiMlEndpoint: string;
  indicParlerEndpoint?: string;
  publicBaseUrl?: string;
}

const defaultLocalPublicBaseUrl = "http://127.0.0.1:8787";
const defaultRemotePublicBaseUrl = "https://ai.silverlining.com.np/voice";

const insuranceReceptionistPrompt = [
  "You are Sarita, a warm Nepali front-desk receptionist for Sagarmatha Lumbini Insurance Company Limited.",
  "If you use the short brand name SALICO, pronounce it as one word: सा-लि-को. Do not spell it letter by letter. When in doubt, say Sagarmatha Lumbini Insurance.",
  "Sagarmatha Lumbini Insurance is a Nepal non-life insurance company serving personal and corporate customers.",
  "You can help with property, motor, marine, engineering, aviation, agriculture, micro, and miscellaneous insurance enquiries.",
  "For official contact details, use 1660-01-66666, +977-1-4529042, +977-1-4529043, info@salico.com.np, customer.service@salico.com.np, and claims@salico.com.np.",
  "Speak Nepali in Devanagari by default. Use English only when the caller clearly starts in English or asks for English.",
  "Only handle Nepali, English, or natural Nepali-English mixed speech. Do not answer in Newari, Hindi, or any other language.",
  "If the caller uses Newari, Hindi, or another unsupported language, say in Nepali: माफ गर्नुहोस्, म नेपाली वा English मा मात्रै सहयोग गर्न सक्छु। कृपया नेपाली वा English मा भन्नुहुन्छ?",
  "Do not infer an insurance product from Newari, unclear mixed speech, or speech recognition noise. Ask the caller to repeat in Nepali or English instead of guessing.",
  "Treat phrases like पति पार्स तो इंचरेंस गरिक्प, उड़ा इन्सुर्यन्स गौन, ति पार्सा, गौन रुपो, and जिवन्ने मैले as unsupported or unclear speech even if they contain the word insurance.",
  "If the caller remains unclear after two attempts, collect their name and phone number for a callback instead of repeating the same question.",
  "This is a live phone call, not a chat. Sound natural, calm, and helpful.",
  "Keep most replies to one short sentence. Use two short sentences only when confirming a next step.",
  "Never repeat the same word or phrase more than twice. If you are unsure, ask one short clarification question instead of filling space.",
  "For policy status, do not claim you checked the system unless a tool result says so. Without a lookup result, say the policy number is noted and staff will verify it; never say active, inactive, expired, pending, or approved.",
  "Use a normal Nepali call-center pace: clear, respectful, and slightly brisk. Do not sound slow, ceremonial, casual, or robotic.",
  "Use natural Nepali phrasing and rhythm. Use familiar Nepali insurance terms. Avoid Hindi-style or Indian call-center intonation where possible.",
  "Use हस् or हजुर for acknowledgement. Do not say ठीक छ.",
  "Use fillers sparingly; avoid filler if the next useful question is obvious.",
  "Handle caller intents for new quotes, policy questions, claims intake, billing, document requests, office hours, and callbacks.",
  "Ask one question at a time. Do not ask for information the caller already gave.",
  "Do not ask how you can help if the caller already stated the purpose.",
  "Silently remember the caller's name, callback phone number, reason for calling, insurance type, policy number, claim number, and next action.",
  "Ask for the most important missing detail next, in this order when relevant: reason, name, phone number, insurance type, policy or claim number.",
  "When repeating phone numbers, policy numbers, claim numbers, account numbers, or reference numbers, say digits one by one or in short groups. Never read them as a full amount value.",
  "Format those numbers with spaces between digits or groups, for example ९८० १२३ ४५६७, not 9801234567.",
  "If speech recognition is unclear, ask a brief clarification instead of guessing.",
  "Do not invent premiums, coverage decisions, claim approvals, policy status, or legal advice.",
  "If a licensed agent, underwriter, or claims handler is required, explain that you can collect details and arrange follow-up.",
  "For emergencies or immediate safety issues, tell the caller to contact local emergency services first.",
  "Before ending, confirm the next step and repeat callback details.",
].join(" ");

export function createDefaultWorkspace(now = new Date().toISOString()): {
  agents: Agent[];
  modelRuntimes: ModelRuntime[];
  modelAssets: ModelAsset[];
  voices: Voice[];
  voiceSamples: VoiceSample[];
  consentRecords: ConsentRecord[];
  tools: Tool[];
  phoneNumbers: PhoneNumber[];
  customers: Customer[];
  tickets: Ticket[];
  appointments: Appointment[];
  transfers: TransferRecord[];
  knowledgeBases: KnowledgeBase[];
  knowledgeDocuments: KnowledgeDocument[];
  evals: EvalDefinition[];
  settings: WorkspaceSettings;
} {
  return {
    agents: [
      {
        id: "agent_reception",
        name: "Reception Agent",
        greeting: "Hi, this is LipiVoice. How can I help?",
        systemPrompt:
          "Answer concisely, ask one question at a time, and collect the caller's name.",
        language: "en",
        modelRuntimeId: "runtime_ollama",
        modelAssetId: "model_llama32_3b",
        voiceId: "voice_piper_amy",
        transcriberRuntimeId: "runtime_whisper_cpp",
        recordingEnabled: false,
        interruptionSensitivity: "medium",
        toolIds: [],
        knowledgeBaseIds: ["kb_reception_faq"],
        deploymentState: "draft",
        createdAt: now,
        updatedAt: now,
      },
    ],
    modelRuntimes: [
      {
        id: "runtime_ollama",
        kind: "llm",
        adapter: "ollama",
        endpoint: "http://127.0.0.1:11434",
        configuredState: "configured",
        healthStatus: "unknown",
        defaultModelId: "model_llama32_3b",
        concurrencyLimit: 1,
        hardwareHints: ["local"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_whisper_cpp",
        kind: "stt",
        adapter: "whisper_cpp",
        endpoint: "",
        configuredState: "not_configured",
        healthStatus: "missing_model",
        defaultModelId: "model_whisper_base_en",
        concurrencyLimit: 1,
        hardwareHints: ["cpu", "metal"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_piper",
        kind: "tts",
        adapter: "piper",
        endpoint: "",
        configuredState: "not_configured",
        healthStatus: "missing_model",
        defaultModelId: "model_piper_amy",
        concurrencyLimit: 1,
        hardwareHints: ["cpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_piper_http",
        kind: "tts",
        adapter: "piper_http",
        endpoint: "http://127.0.0.1:5002",
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_piper_ne_http",
        concurrencyLimit: 4,
        hardwareHints: ["cpu", "service"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_coqui_http",
        kind: "tts",
        adapter: "coqui_http",
        endpoint: "http://127.0.0.1:5003",
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_coqui_xtts_ne",
        concurrencyLimit: 2,
        hardwareHints: ["gpu", "service"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_fastpitch_http",
        kind: "tts",
        adapter: "fastpitch_http",
        endpoint: "http://127.0.0.1:5004",
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_fastpitch_ne",
        concurrencyLimit: 2,
        hardwareHints: ["gpu", "service"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_faster_whisper",
        kind: "stt",
        adapter: "faster_whisper",
        endpoint: "http://127.0.0.1:9000",
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_faster_whisper_ne",
        concurrencyLimit: 4,
        hardwareHints: ["cpu", "gpu", "service"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_indic_parler",
        kind: "tts",
        adapter: "indic_parler",
        endpoint: "http://127.0.0.1:5010",
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_indic_parler_ne_finetuned",
        concurrencyLimit: 1,
        hardwareHints: ["remote", "gpu", "hf-model"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_energy_vad",
        kind: "vad",
        adapter: "energy_vad",
        endpoint: "local",
        configuredState: "configured",
        healthStatus: "healthy",
        defaultModelId: "energy_threshold_v1",
        concurrencyLimit: 4,
        hardwareHints: ["cpu"],
        createdAt: now,
        updatedAt: now,
      },
    ],
    modelAssets: [
      {
        id: "model_llama32_3b",
        runtimeId: "runtime_ollama",
        name: "LipiCore Local",
        kind: "llm",
        family: "llama",
        version: "3.2",
        pathOrTag: "llama3.2:3b",
        license: "Meta Llama license",
        parameterSize: "3B",
        quantization: "provider default",
        languageSupport: ["en"],
        installedState: "unknown",
      },
      {
        id: "model_gemma_4b",
        runtimeId: "runtime_ollama",
        name: "Gemma 4B (Nepali-capable)",
        kind: "llm",
        family: "gemma",
        version: "3",
        pathOrTag: "gemma3:4b",
        license: "Google Gemma Terms",
        parameterSize: "4B",
        quantization: "provider default",
        languageSupport: ["ne", "en"],
        installedState: "unknown",
      },
      {
        id: "model_whisper_base_en",
        runtimeId: "runtime_whisper_cpp",
        name: "LipiHear Local English",
        kind: "stt",
        family: "whisper",
        version: "base.en",
        pathOrTag: "ggml-base.en.bin",
        license: "MIT",
        parameterSize: "74M",
        quantization: "ggml",
        languageSupport: ["en"],
        installedState: "unknown",
      },
      {
        id: "model_piper_amy",
        runtimeId: "runtime_piper",
        name: "LipiVoice Local Amy",
        kind: "tts",
        family: "piper",
        version: "amy",
        pathOrTag: "en_US-amy-low.onnx",
        license: "MIT",
        parameterSize: "n/a",
        quantization: "onnx",
        languageSupport: ["en-US"],
        installedState: "unknown",
      },
      {
        id: "model_piper_ne_http",
        runtimeId: "runtime_piper_http",
        name: "Piper Nepali (HTTP)",
        kind: "tts",
        family: "piper",
        version: "ne",
        pathOrTag: "ne_NP-google-medium",
        license: "Apache-2.0",
        parameterSize: "n/a",
        quantization: "onnx",
        languageSupport: ["ne-NP"],
        installedState: "unknown",
      },
      {
        id: "model_coqui_xtts_ne",
        runtimeId: "runtime_coqui_http",
        name: "Coqui XTTS v2 (Nepali)",
        kind: "tts",
        family: "xtts",
        version: "v2",
        pathOrTag: "tts_models/multilingual/multi-dataset/xtts_v2",
        license: "Coqui Public Model License",
        parameterSize: "~1B",
        quantization: "fp32",
        languageSupport: ["ne", "en", "multilingual"],
        installedState: "unknown",
      },
      {
        id: "model_fastpitch_ne",
        runtimeId: "runtime_fastpitch_http",
        name: "FastPitch Nepali",
        kind: "tts",
        family: "fastpitch",
        version: "1.1",
        pathOrTag: "fastpitch:ne-NP",
        license: "Apache-2.0",
        parameterSize: "~45M",
        quantization: "fp32",
        languageSupport: ["ne-NP"],
        installedState: "unknown",
      },
      {
        id: "model_indic_parler_ne_finetuned",
        runtimeId: "runtime_indic_parler",
        name: "Indic Parler Nepali Fine-tune",
        kind: "tts",
        family: "parler-tts",
        version: "dgx-v9-cosine",
        pathOrTag: "milanakdj/indic-parler-tts-nepali-finetuned-dgx-v9-cosine",
        license: "license-unconfirmed",
        parameterSize: "0.9B",
        quantization: "fp32",
        languageSupport: ["ne"],
        installedState: "unknown",
      },
      {
        id: "model_faster_whisper_ne",
        runtimeId: "runtime_faster_whisper",
        name: "Faster-Whisper Nepali (large-v3)",
        kind: "stt",
        family: "whisper",
        version: "large-v3",
        pathOrTag: "large-v3",
        license: "MIT",
        parameterSize: "1.5B",
        quantization: "int8",
        languageSupport: ["ne", "en"],
        installedState: "unknown",
      },
      {
        id: "energy_threshold_v1",
        runtimeId: "runtime_energy_vad",
        name: "Energy threshold VAD",
        kind: "vad",
        family: "energy_vad",
        version: "1",
        pathOrTag: "local:energy-threshold-v1",
        license: "MIT",
        parameterSize: "n/a",
        quantization: "n/a",
        languageSupport: [],
        installedState: "installed",
      },
    ],
    voices: [
      {
        id: "voice_piper_amy",
        name: "Asha",
        runtimeId: "runtime_piper",
        type: "builtin",
        language: "en-US",
        tags: ["local", "neutral"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
      {
        id: "voice_piper_ne",
        name: "Sarita (Piper)",
        runtimeId: "runtime_piper_http",
        type: "builtin",
        language: "ne-NP",
        tags: ["open-source", "piper", "nepali", "fast"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
      {
        id: "voice_coqui_ne",
        name: "Maya (Coqui XTTS)",
        runtimeId: "runtime_coqui_http",
        type: "builtin",
        language: "ne-NP",
        tags: ["open-source", "coqui", "nepali", "expressive"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
      {
        id: "voice_fastpitch_ne",
        name: "Anita (FastPitch)",
        runtimeId: "runtime_fastpitch_http",
        type: "builtin",
        language: "ne-NP",
        tags: ["open-source", "fastpitch", "nepali", "gpu"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
      ...createLipiVoiceNepaliVoices(),
    ],
    voiceSamples: [],
    consentRecords: [],
    tools: createSeedTools(now),
    phoneNumbers: createSeedPhoneNumbers(now),
    customers: [],
    tickets: [],
    appointments: [],
    transfers: [],
    knowledgeBases: createSeedKnowledgeBases(now),
    knowledgeDocuments: createSeedKnowledgeDocuments(now),
    evals: createSeedEvals(now),
    settings: createSeedSettings(now, defaultLocalPublicBaseUrl),
  };
}

export function createRemoteWorkspace(options: RemoteWorkspaceOptions): {
  agents: Agent[];
  modelRuntimes: ModelRuntime[];
  modelAssets: ModelAsset[];
  voices: Voice[];
  voiceSamples: VoiceSample[];
  consentRecords: ConsentRecord[];
  tools: Tool[];
  phoneNumbers: PhoneNumber[];
  customers: Customer[];
  tickets: Ticket[];
  appointments: Appointment[];
  transfers: TransferRecord[];
  knowledgeBases: KnowledgeBase[];
  knowledgeDocuments: KnowledgeDocument[];
  evals: EvalDefinition[];
  settings: WorkspaceSettings;
} {
  const now = options.now ?? new Date().toISOString();
  const vllmEndpoint = trimTrailingSlash(options.vllmEndpoint);
  const lipiMlEndpoint = trimTrailingSlash(options.lipiMlEndpoint);
  const indicParlerEndpoint = trimTrailingSlash(options.indicParlerEndpoint ?? "http://127.0.0.1:5010");

  return {
    agents: [
      {
        id: "agent_reception",
        name: "Sarita",
        greeting:
          "नमस्ते, सगरमाथा लुम्बिनी इन्स्योरेन्समा स्वागत छ। म सरिता बोल्दैछु, म कसरी सहयोग गर्न सक्छु?",
        systemPrompt: insuranceReceptionistPrompt,
        language: "ne",
        modelRuntimeId: "runtime_vllm",
        modelAssetId: "model_vllm_remote",
        voiceId: "voice_lipi_ml_ne",
        transcriberRuntimeId: "runtime_lipi_ml_stt",
        recordingEnabled: false,
        interruptionSensitivity: "medium",
        toolIds: [
          "tool_collect_callback",
          "tool_claim_intake",
          "tool_document_request",
          "tool_office_hours",
        ],
        knowledgeBaseIds: ["kb_reception_faq"],
        deploymentState: "ready",
        createdAt: now,
        updatedAt: now,
      },
    ],
    modelRuntimes: [
      {
        id: "runtime_vllm",
        kind: "llm",
        adapter: "vllm",
        endpoint: vllmEndpoint,
        configuredState: "configured",
        healthStatus: "unknown",
        defaultModelId: "model_vllm_remote",
        concurrencyLimit: 2,
        hardwareHints: ["remote", "gpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_lipi_ml_stt",
        kind: "stt",
        adapter: "faster_whisper",
        endpoint: `${lipiMlEndpoint}/stt`,
        configuredState: "configured",
        healthStatus: "unknown",
        defaultModelId: "model_lipi_ml_whisper_large_v3",
        concurrencyLimit: 1,
        hardwareHints: ["remote", "gpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_lipi_ml_tts",
        kind: "tts",
        adapter: "piper",
        endpoint: `${lipiMlEndpoint}/tts`,
        configuredState: "configured",
        healthStatus: "unknown",
        defaultModelId: "model_lipi_ml_piper",
        concurrencyLimit: 4,
        hardwareHints: ["remote", "cpu", "gpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_piper_http",
        kind: "tts",
        adapter: "piper_http",
        endpoint: `${lipiMlEndpoint}/tts`,
        configuredState: "configured",
        healthStatus: "unknown",
        defaultModelId: "model_lipi_ml_piper",
        concurrencyLimit: 4,
        hardwareHints: ["remote", "cpu", "gpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_coqui_http",
        kind: "tts",
        adapter: "coqui_http",
        endpoint: `${lipiMlEndpoint}/coqui`,
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_coqui_xtts_ne",
        concurrencyLimit: 2,
        hardwareHints: ["remote", "gpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_fastpitch_http",
        kind: "tts",
        adapter: "fastpitch_http",
        endpoint: `${lipiMlEndpoint}/fastpitch`,
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_fastpitch_ne",
        concurrencyLimit: 2,
        hardwareHints: ["remote", "gpu"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_indic_parler",
        kind: "tts",
        adapter: "indic_parler",
        endpoint: indicParlerEndpoint,
        configuredState: "not_configured",
        healthStatus: "unknown",
        defaultModelId: "model_indic_parler_ne_finetuned",
        concurrencyLimit: 1,
        hardwareHints: ["remote", "gpu", "hf-model"],
        createdAt: now,
        updatedAt: now,
      },
      {
        id: "runtime_energy_vad",
        kind: "vad",
        adapter: "energy_vad",
        endpoint: "local",
        configuredState: "configured",
        healthStatus: "healthy",
        defaultModelId: "energy_threshold_v1",
        concurrencyLimit: 4,
        hardwareHints: ["cpu"],
        createdAt: now,
        updatedAt: now,
      },
    ],
    modelAssets: [
      {
        id: "model_vllm_remote",
        runtimeId: "runtime_vllm",
        name: "LipiCore Realtime",
        kind: "llm",
        family: "gemma",
        version: "remote",
        pathOrTag: options.vllmModel,
        license: "model license from installed remote asset",
        parameterSize: "remote",
        quantization: "provider default",
        languageSupport: ["en", "ne"],
        installedState: "installed",
      },
      {
        id: "model_lipi_ml_whisper_large_v3",
        runtimeId: "runtime_lipi_ml_stt",
        name: "LipiHear Remote",
        kind: "stt",
        family: "whisper",
        version: "large-v3",
        pathOrTag: "lipi-ml:lipihear-large-v3",
        license: "MIT",
        parameterSize: "large",
        quantization: "provider default",
        languageSupport: ["en", "ne"],
        installedState: "installed",
      },
      {
        id: "model_lipi_ml_piper",
        runtimeId: "runtime_lipi_ml_tts",
        name: "LipiVoice Remote",
        kind: "tts",
        family: "piper",
        version: "remote",
        pathOrTag: "lipi-ml:piper",
        license: "LipiVoice remote runtime terms",
        parameterSize: "n/a",
        quantization: "onnx",
        languageSupport: ["en-US", "ne-NP"],
        installedState: "installed",
      },
      {
        id: "model_coqui_xtts_ne",
        runtimeId: "runtime_coqui_http",
        name: "Coqui XTTS v2 (Nepali)",
        kind: "tts",
        family: "xtts",
        version: "v2",
        pathOrTag: "tts_models/multilingual/multi-dataset/xtts_v2",
        license: "Coqui Public Model License",
        parameterSize: "~1B",
        quantization: "fp32",
        languageSupport: ["ne", "en", "multilingual"],
        installedState: "unknown",
      },
      {
        id: "model_fastpitch_ne",
        runtimeId: "runtime_fastpitch_http",
        name: "FastPitch Nepali",
        kind: "tts",
        family: "fastpitch",
        version: "1.1",
        pathOrTag: "fastpitch:ne-NP",
        license: "Apache-2.0",
        parameterSize: "~45M",
        quantization: "fp32",
        languageSupport: ["ne-NP"],
        installedState: "unknown",
      },
      {
        id: "model_indic_parler_ne_finetuned",
        runtimeId: "runtime_indic_parler",
        name: "Indic Parler Nepali Fine-tune",
        kind: "tts",
        family: "parler-tts",
        version: "dgx-v9-cosine",
        pathOrTag: "milanakdj/indic-parler-tts-nepali-finetuned-dgx-v9-cosine",
        license: "license-unconfirmed",
        parameterSize: "0.9B",
        quantization: "fp32",
        languageSupport: ["ne"],
        installedState: "unknown",
      },
      {
        id: "energy_threshold_v1",
        runtimeId: "runtime_energy_vad",
        name: "Energy threshold VAD",
        kind: "vad",
        family: "energy_vad",
        version: "1",
        pathOrTag: "local:energy-threshold-v1",
        license: "MIT",
        parameterSize: "n/a",
        quantization: "n/a",
        languageSupport: [],
        installedState: "installed",
      },
    ],
    voices: [
      ...createLipiVoiceNepaliVoices(),
      {
        id: "voice_lipi_ml_en",
        name: "Asha",
        runtimeId: "runtime_lipi_ml_tts",
        type: "builtin",
        language: "en-US",
        tags: ["remote", "piper", "english"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
      {
        id: "voice_lipi_ml_ne",
        name: "Mina",
        runtimeId: "runtime_lipi_ml_tts",
        type: "builtin",
        language: "ne-NP",
        tags: ["remote", "piper", "nepali", "native-target"],
        previewUrl: "",
        privacy: "workspace",
        cloneStatus: "not_clone",
        consentId: null,
      },
    ],
    voiceSamples: [],
    consentRecords: [],
    tools: createSeedTools(now),
    phoneNumbers: createSeedPhoneNumbers(now),
    customers: [],
    tickets: [],
    appointments: [],
    transfers: [],
    knowledgeBases: createSeedKnowledgeBases(now),
    knowledgeDocuments: createSeedKnowledgeDocuments(now),
    evals: createSeedEvals(now),
    settings: createSeedSettings(now, options.publicBaseUrl ?? defaultRemotePublicBaseUrl),
  };
}

function createLipiVoiceNepaliVoices(): Voice[] {
  return [
    { id: "voice_piper_ne_sita", name: "Sita (Piper)", runtimeId: "runtime_piper_http", tags: ["piper", "nepali", "female", "fast"] },
    { id: "voice_piper_ne_maya", name: "Maya (Piper)", runtimeId: "runtime_piper_http", tags: ["piper", "nepali", "female", "fast"] },
    { id: "voice_coqui_ne_anju", name: "Anju (Coqui)", runtimeId: "runtime_coqui_http", tags: ["coqui", "nepali", "female", "expressive"] },
    { id: "voice_coqui_ne_kiran", name: "Kiran (Coqui)", runtimeId: "runtime_coqui_http", tags: ["coqui", "nepali", "male", "expressive"] },
    { id: "voice_fastpitch_ne_nabin", name: "Nabin (FastPitch)", runtimeId: "runtime_fastpitch_http", tags: ["fastpitch", "nepali", "male", "gpu"] },
    { id: "voice_fastpitch_ne_bikram", name: "Bikram (FastPitch)", runtimeId: "runtime_fastpitch_http", tags: ["fastpitch", "nepali", "male", "gpu"] },
    { id: "voice_indic_parler_ne_amrita", name: "Amrita (Indic Parler)", runtimeId: "runtime_indic_parler", tags: ["indic-parler", "nepali", "female", "evaluation"] },
  ].map((voice) => ({
    ...voice,
    type: "builtin" as const,
    language: "ne-NP",
    previewUrl: "",
    privacy: "workspace" as const,
    cloneStatus: "not_clone" as const,
    consentId: null,
  }));
}

function createSeedTools(now: string): Tool[] {
  return [
    {
      id: "tool_collect_callback",
      name: "Collect callback",
      description: "Record caller details for a licensed insurance staff callback.",
      method: "POST",
      url: "https://example.com/insurance/callbacks",
      authMode: "none",
      headers: [],
      parameters: [
        { name: "name", type: "string", required: true },
        { name: "phoneNumber", type: "string", required: true },
        { name: "reason", type: "string", required: true },
      ],
      timeoutMs: 5000,
      retryCount: 0,
      responseSchema: "{\"ok\":\"boolean\",\"callbackId\":\"string\"}",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tool_claim_intake",
      name: "Claim intake",
      description: "Record initial claim details without approving or denying the claim.",
      method: "POST",
      url: "https://example.com/insurance/claims/intake",
      authMode: "none",
      headers: [],
      parameters: [
        { name: "name", type: "string", required: true },
        { name: "phoneNumber", type: "string", required: true },
        { name: "claimType", type: "string", required: true },
        { name: "incidentSummary", type: "string", required: true },
      ],
      timeoutMs: 5000,
      retryCount: 0,
      responseSchema: "{\"ok\":\"boolean\",\"intakeId\":\"string\"}",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tool_document_request",
      name: "Document request",
      description: "Record a request for insurance documents or policy paperwork.",
      method: "POST",
      url: "https://example.com/insurance/documents/request",
      authMode: "none",
      headers: [],
      parameters: [
        { name: "name", type: "string", required: true },
        { name: "phoneNumber", type: "string", required: true },
        { name: "documentType", type: "string", required: true },
      ],
      timeoutMs: 5000,
      retryCount: 0,
      responseSchema: "{\"ok\":\"boolean\",\"requestId\":\"string\"}",
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "tool_office_hours",
      name: "Office hours",
      description: "Return Lipi Insurance office hours and callback availability.",
      method: "GET",
      url: "https://example.com/insurance/office-hours",
      authMode: "none",
      headers: [],
      parameters: [],
      timeoutMs: 5000,
      retryCount: 0,
      responseSchema: "{\"hours\":\"string\",\"timezone\":\"string\"}",
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function createSeedPhoneNumbers(now: string): PhoneNumber[] {
  return [
    {
      id: "phone_demo_main",
      label: "Main reception line",
      number: "+15551201001",
      provider: "simulation",
      status: "active",
      agentId: "agent_reception",
      inboundEnabled: true,
      outboundEnabled: false,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function createSeedKnowledgeBases(now: string): KnowledgeBase[] {
  return [
    {
      id: "kb_reception_faq",
      name: "Insurance Reception FAQ",
      description: "Default caller-facing answers for the insurance reception agent.",
      status: "ready",
      documentCount: 1,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function createSeedKnowledgeDocuments(now: string): KnowledgeDocument[] {
  return [
    {
      id: "doc_reception_hours",
      knowledgeBaseId: "kb_reception_faq",
      title: "Insurance reception basics",
      sourceType: "text",
      content:
        "Lipi Insurance reception can help callers with new quotes, policy questions, claims intake, billing questions, document requests, office hours, and callback scheduling. Reception is available Monday through Friday from 9 AM to 5 PM. Receptionists should collect the caller's name, phone number, insurance type, and policy or claim number when available.",
      tokenCount: 53,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function createSeedEvals(now: string): EvalDefinition[] {
  return [
    {
      id: "eval_nepali_reception_greeting",
      name: "Nepali reception greeting",
      description: "Checks that the reception agent greets as Lipi Insurance in Nepali.",
      agentId: "agent_reception",
      cases: [
        {
          id: "case_nepali_greeting",
          input: "नमस्ते",
          checks: [
            { type: "includes", value: "लिपि" },
            { type: "excludes", value: "premium approved" },
          ],
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "eval_claim_no_approval",
      name: "Claim intake without approval",
      description: "Checks that the receptionist does not approve or deny claims.",
      agentId: "agent_reception",
      cases: [
        {
          id: "case_claim_no_approval",
          input: "मेरो दुर्घटनाको claim approve हुन्छ?",
          checks: [
            { type: "includes", value: "claims" },
            { type: "excludes", value: "approved" },
          ],
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
    {
      id: "eval_callback_collection",
      name: "Callback collection",
      description: "Checks that the receptionist asks for callback details.",
      agentId: "agent_reception",
      cases: [
        {
          id: "case_callback",
          input: "मलाई agent ले call back गर्नुपर्‍यो",
          checks: [
            { type: "includes", value: "phone" },
            { type: "includes", value: "name" },
          ],
        },
      ],
      createdAt: now,
      updatedAt: now,
    },
  ];
}

function createSeedSettings(now: string, publicBaseUrl: string): WorkspaceSettings {
  const normalizedPublicBaseUrl = trimTrailingSlash(publicBaseUrl) || defaultLocalPublicBaseUrl;
  const origin = new URL(normalizedPublicBaseUrl).origin;

  return {
    id: "workspace_settings",
    workspaceName: "LipiVoice",
    publicBaseUrl: normalizedPublicBaseUrl,
    allowedOrigins: [origin],
    allowPrivateToolUrls: false,
    redactToolSecrets: true,
    recordingRetentionDays: 30,
    auditLogRetentionDays: 90,
    realtimeSessionTtlSeconds: 60,
    sipTrunk: {
      enabled: false,
      provider: "",
      mode: "asterisk",
      sipServer: "",
      outboundProxy: "",
      domain: "",
      username: "",
      authUsername: "",
      fromNumber: "",
      transport: "udp",
    },
    createdAt: now,
    updatedAt: now,
  };
}

function trimTrailingSlash(value: string): string {
  return value.replace(/\/+$/, "");
}
