[general]
static=yes
writeprotect=yes
clearglobalvars=no

[globals]

[from-livekit]
exten => _X!,1,NoOp(LipiVoice outbound via NTC: ${EXTEN})
 same => n,Dial(PJSIP/${EXTEN}@ntc,60)
 same => n,Hangup()

[from-ntc]
exten => _X!,1,NoOp(NTC inbound call for ${EXTEN})
 same => n,Hangup()

exten => s,1,NoOp(NTC inbound call)
 same => n,Hangup()
